---
- name: List Variables
  hosts: all
  vars:
  #- my_hash: "{{ hash_string | from_json }}"
  
  tasks:
  - set_fact: myhash="{{ hash_string | from_json }}"
  - debug: var=array
  - debug: var=myhash
  