---
- name: List Variables
  hosts: all
  vars:
  - my_hash: "{{ string_hash }}"
  
  tasks:
  #- set_fact: my_hash="{{ my_hash | from_json }}"
  - debug: var=my_array
  - debug: var=string_hash
  - debug: var=my_hash
  - debug: msg="The key is {{ item.key }} and the value is {{ item.value }}"
    with_dict: "{{ my_hash }}"
  