---
- name: List Variables
  hosts: all
  vars:
  #- my_hash: "{{ string_hash | from_json }}"
  
  tasks:
  - set_fact: my_hash="{{ string_hash | from_json }}"
  - debug: var=my_array
  - debug: var=my_hash
  