---
- name: List Variables
  hosts: all

  tasks:
  - debug: var=my_array
  - debug: var=string_hash
  - debug: msg="The key is {{ item.key }} and the value is {{ item.value }}"
    with_dict: "{{ string_hash }}"
  