---
- name: List Variables on localhost
  hosts: all

  tasks:
  - debug: var=hostvars[inventory_hostname]

- name: List Variables
  hosts: "{{ vm_target_name }}"
  vars: 
    vm_target_name:

  tasks:
  - debug: var=hostvars[inventory_hostname].cloudforms
  - debug: var=hostvars[inventory_hostname]
