---
- name: manageiq-vmdb role example usage
  hosts: localhost
  connection: local

  roles:
  - manageiq-core.manageiq-vmdb

  tasks:
  - name: Get a vmdb object
    manageiq_vmdb:
      href: "{{ manageiq.service }}"
    register: service
    
  - name: Print the service details
    debug:
      msg: "Services object is {{ service }}"
          
  - name: Rename the service
    manageiq_vmdb:
      vmdb: "{{ service }}"
      action: edit
      data:
        name: "manageiq-vmdb role example usage"
        description: "manageiq-vmdb role example usage run on {{ lookup('pipe', 'date +%Y-%m-%d\\ %H:%M') }}"

  - name: Get the VM object
    manageiq_vmdb:
      href: "vms?filter[]=name=fred_vm_2"
    register: vm
  - set_fact:
      vm_href: "{{ vm.resources[0].href }}"
      
  - name: print the VM's href
    debug:
      msg: "VM href: {{ vm_href }}"
      
  - name: Add the VM to the service
    manageiq_vmdb:
      vmdb: "{{ service }}"
      action: add_resource
      data:
        resource:
          href: "{{ vm_href }}"
          
