---
- name: manageiq-vmdb role example usage
  hosts: localhost
  connection: local

  roles:
  - manageiq-core.manageiq-vmdb

  tasks:
  - name: Get a vmdb object
    manageiq_vmdb:
      href: "{{ manageiq.service }}"
    register: service
    
  - name: Print the service details
    debug:
      msg: "Services object is {{ service }}"
      
  #{
  #   "action" : "edit",
  #   "resource" : {
  #     "name" : "Updated Service Name",
  #     "description" : "Updated Service Description"
  #   }
  #}
      
  - name: Rename the service
    manageiq_vmdb:
      vmdb: "{{ service }}"
      action: edit
      data:
        name: "manageiq-vmdb role example usage"
        description: "manageiq-vmdb role example usage run on {{ lookup('pipe', 'date +%Y-%m-%d\\ %H:%M') }}"

  #{
  #  "action" : "add_provider_vms",
  #  "resource" : {
  #    "provider" : { "href" : "http://localhot:3000/api/providers/11" }
  #    "uid_ems" : [
  #      "provider_vm_id1",
  #      "provider_vm_id2",
  #      ...
  #    ]
  #  }
  #}
  
    #- name: Service Linking via an href slug
    #manageiq_vmdb:
    #  href: "href_slug::services/80"
    #  action: add_provider_vms
    #  data:
    #    uid_ems:
    #      - "{{ ec2.instances[0].id }}"
    #    provider:
    #      id: 24

  - name: Add the VM to the service
    manageiq_vmdb:
      vmdb: "{{ service }}"
      action: add_resource
      data:
        resource:
          href: "href_slug::vms/18"
