---
- name: manageiq-vmdb role example usage
  hosts: localhost
  connection: local
  vars:
  - manageiq_validate_certs: false

  roles:
  - manageiq-core.manageiq-vmdb

  tasks:
  - name: Get a vmdb object
    manageiq_vmdb:
      href: "{{ manageiq.service }}"
    register: service
    
  - name: Print the service details
    debug:
      msg: "Services object is {{ service }}"
          
  - name: Rename the service
    manageiq_vmdb:
      vmdb: "{{ service }}"
      action: edit
      data:
        name: "manageiq-vmdb role example usage"
        description: "manageiq-vmdb role example usage run on {{ lookup('pipe', 'date +%Y-%m-%d\\ %H:%M') }}"
        
  - name: Get the VM object
    uri:
      url: "{{ manageiq.api_url }}/api/vms?filter[]=name=cloudforms04.bit63.net"
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type:  application/json
      body_format: json
    register: vm
  #- set_fact:
  #    vm_href: "{{ vm.resources[0].href }}"
      
  - name: print the VM
    debug:
      msg: "VM: {{ vm }}"
      
  #- name: Add the VM to the service
  #  manageiq_vmdb:
  #    vmdb: "{{ service }}"
  #    action: add_resource
  #    data:
  #      resource:
  #        href: "{{ vm_href }}"
          
