---
- name: Password input parameter test
  hosts: localhost
  connection: local
  
  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate
  
  tasks:
  - name: Get the list of method parameters (get_method_parameters)
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_method_parameters: yes
    register: get_method_parameters
  - debug: msg="Result:{{ get_method_parameters.value }}"
    
  - name: print the default_password value
    debug:
      msg: "default_password is {{ default_password }}"
    when: default_password is defined
      
  - name: print the default_passwd value
    debug:
      msg: "default_passwd is {{ default_passwd }}"
    when: default_passwd is defined