---
- name: Setup firewall ports on Tower cluster nodes
  hosts: all
  
  tasks:

  - firewalld:
      service: "{{ item }}"
      immediate: true
      permanent: true
      state: enabled
    with_items:
      - http
      - https
      
  - firewalld:
      port: "{{ item }}/tcp"
      immediate: true
      permanent: true
      state: enabled
    with_items:
      - 4369
      - 25672
      - 15672