---
- name: manageiq-automate role example usage
  hosts: localhost
  connection: local

  gather_facts: False
  roles:
  - syncrou.manageiq-automate
  
  tasks:
    
    - debug: msg="dialog_options_to_s:{{ dialog_options_to_s }}"
    - debug: msg="dialog_options_to_yaml:{{ dialog_options_to_yaml }}"
    #- debug: msg="Dialog option name - {{ item.key }} with value - {{ item.value }}"
    #  with_dict: "{{ dialog_options }}"
    
    #- name: Decrypt a method_parameter called 'root_password' (get_decrypted_method_parameter)
    #  manageiq_automate:
    #    workspace: "{{ workspace }}"
    #    get_decrypted_method_parameter:
    #      attribute: 'dialog_options.password::dialog_option_0_root_password'
    #  register: decrypted_method_parameter
    #- debug: msg=Result:{{ decrypted_method_parameter.value }}
